apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tmwebapp
  name: tmwebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tmwebapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tmwebapp
    spec:
      containers:
      - image: trenditalydocker/webpage@sha256:2d114f5192df7d45391b35f61901a6b8623342de66cea57bb2ca0d50341084d6
        name: tmwebapp
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: tmwebapp
