apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tmwebapp
  name: tmwebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tmwebapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tmwebapp
    spec:
      containers:
      - image: trenditalydocker/webpage@sha256:74813ac159725cc5908277d3e70042c488db5f97fb1f97569160625412afc3fd
        name: tmwebapp
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: tmwebapp
